name: Lint & Compile

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "development" branch
    push:
        branches: ["development"]
    pull_request:
        branches: ["development"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: yarn install --immutable
            - name: Restyle with prettier
              uses: actionsx/prettier@v2
              with:
                  args: --write src/
            - name: Fix low-hanging eslint errors
              run: eslint --fix src/ || true
            - name: Run eslint
              uses: mrdivyansh/eslint-action@v1.0.7
              with:
                  execute-on-files: src/
            - name: Compile
              run: yarn build
            - name: Push
              uses: actions-go/push@v1
              with:
                  author-email: github-actions[bot]@users.noreply.github.com
                  author-name: Linter
                  create-commit: true
                  commit-message: "Reformatted code and fixed linting errors"
